#!/bin/sh

gcc -Wall -Wextra -Wpedantic -std=c11 -fPIC  -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -c -o gstmyaudio.o gstmyaudio.c
  
gcc -shared -o gstmyaudio.so gstmyaudio.o -lgstaudio-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0

gst-inspect-1.0 ./gstmyaudio.so

